// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaJZOb4v7hU_r7EMTRQ_ZrZ5KV4TBntTM',
    appId: '1:326042041475:web:e2c701dadd1938d0eeafb6',
    messagingSenderId: '326042041475',
    projectId: 'people-collection-e343b',
    authDomain: 'people-collection-e343b.firebaseapp.com',
    storageBucket: 'people-collection-e343b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEtk33qRwQTLpUb7_wInwLLQt00d-u3zU',
    appId: '1:326042041475:android:84acd6d6109c9347eeafb6',
    messagingSenderId: '326042041475',
    projectId: 'people-collection-e343b',
    storageBucket: 'people-collection-e343b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwBeDxPFkUNvirONVLNwFn5SmXjy3kalU',
    appId: '1:326042041475:ios:b08025875bc14c4feeafb6',
    messagingSenderId: '326042041475',
    projectId: 'people-collection-e343b',
    storageBucket: 'people-collection-e343b.firebasestorage.app',
    iosBundleId: 'com.example.peopleCollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwBeDxPFkUNvirONVLNwFn5SmXjy3kalU',
    appId: '1:326042041475:ios:b08025875bc14c4feeafb6',
    messagingSenderId: '326042041475',
    projectId: 'people-collection-e343b',
    storageBucket: 'people-collection-e343b.firebasestorage.app',
    iosBundleId: 'com.example.peopleCollection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaJZOb4v7hU_r7EMTRQ_ZrZ5KV4TBntTM',
    appId: '1:326042041475:web:369d4334fca23fc4eeafb6',
    messagingSenderId: '326042041475',
    projectId: 'people-collection-e343b',
    authDomain: 'people-collection-e343b.firebaseapp.com',
    storageBucket: 'people-collection-e343b.firebasestorage.app',
  );
}
